/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        baseblack: "var(--baseblack)",
        basewhite: "var(--basewhite)",
        "blue-100": "var(--blue-100)",
        "blue-200": "var(--blue-200)",
        "blue-50": "var(--blue-50)",
        "blue-700": "var(--blue-700)",
        "blue-dark-700": "var(--blue-dark-700)",
        "error-100": "var(--error-100)",
        "error-200": "var(--error-200)",
        "error-25": "var(--error-25)",
        "error-300": "var(--error-300)",
        "error-50": "var(--error-50)",
        "error-600": "var(--error-600)",
        "error-700": "var(--error-700)",
        "error-800": "var(--error-800)",
        "gray-100": "var(--gray-100)",
        "gray-200": "var(--gray-200)",
        "gray-300": "var(--gray-300)",
        "gray-400": "var(--gray-400)",
        "gray-50": "var(--gray-50)",
        "gray-500": "var(--gray-500)",
        "gray-600": "var(--gray-600)",
        "gray-700": "var(--gray-700)",
        "gray-800": "var(--gray-800)",
        "gray-900": "var(--gray-900)",
        "gray-blue300": "var(--gray-blue300)",
        "moss-300": "var(--moss-300)",
        "orange-dark-300": "var(--orange-dark-300)",
        "primary-100": "var(--primary-100)",
        "primary-200": "var(--primary-200)",
        "primary-25": "var(--primary-25)",
        "primary-300": "var(--primary-300)",
        "primary-50": "var(--primary-50)",
        "primary-600": "var(--primary-600)",
        "primary-700": "var(--primary-700)",
        "primary-800": "var(--primary-800)",
        purple: "var(--purple)",
        "ros-300": "var(--ros-300)",
        "success-200": "var(--success-200)",
        "success-50": "var(--success-50)",
        "success-500": "var(--success-500)",
        "success-700": "var(--success-700)",
        "warning-300": "var(--warning-300)",
      },
      fontFamily: {
        "display-lg-semibold": "var(--display-lg-semibold-font-family)",
        "display-xs-regular": "var(--display-xs-regular-font-family)",
        "display-xs-semibold": "var(--display-xs-semibold-font-family)",
        "text-lg-medium": "var(--text-lg-medium-font-family)",
        "text-lg-regular": "var(--text-lg-regular-font-family)",
        "text-lg-semibold": "var(--text-lg-semibold-font-family)",
        "text-md-medium": "var(--text-md-medium-font-family)",
        "text-md-regular": "var(--text-md-regular-font-family)",
        "text-md-semibold": "var(--text-md-semibold-font-family)",
        "text-sm-semibold": "var(--text-sm-semibold-font-family)",
        "text-xl-medium": "var(--text-xl-medium-font-family)",
        "text-xl-regular": "var(--text-xl-regular-font-family)",
        "text-xl-semibold": "var(--text-xl-semibold-font-family)",
        "text-xs-medium": "var(--text-xs-medium-font-family)",
        "text-xs-semibold": "var(--text-xs-semibold-font-family)",
      },
      boxShadow: {
        "background-blur-sm": "var(--background-blur-sm)",
        "focus-ring-4px-gray-100": "var(--focus-ring-4px-gray-100)",
        "focus-ring-4px-primary-100": "var(--focus-ring-4px-primary-100)",
        "shadow-2xl": "var(--shadow-2xl)",
        "shadow-3xl": "var(--shadow-3xl)",
        "shadow-lg": "var(--shadow-lg)",
        "shadow-xs": "var(--shadow-xs)",
        "shadow-xs-focused-4px-error-100": "var(--shadow-xs-focused-4px-error-100)",
        "shadow-xs-focused-4px-gray-100": "var(--shadow-xs-focused-4px-gray-100)",
        "shadow-xs-focused-4px-primary-100": "var(--shadow-xs-focused-4px-primary-100)",
      },
    },
  },
  plugins: [],
};
